metric = {
    "length": "meter",
    "time": "second",
    "amount_of_substance": "mole",
    "temperature": "kelvin",
    "luminous_intensity": "candela",
    "mass": "kilogram",

    "force": "newton",
    "energy": "joule",
    "electric_charge": "coulomb",
    "catalytic_activity": "katal",
    "illuminance": "lux",
    "power": "watt",
    "stress": "Pa",
    "voltage": "volt",
    "magnetic_flux": "weber",
    "magnetic_flux_density": "tesla",
    "luminous_flux": "lumen",
    "frequency": "hertz",
    "activity": "becquerel",
    "dose": "gray",
    "resistance": "ohm",
    "inductance": "henry",
    "capacitance": "farad",
    "solid_angle": "steradian",
    "dose_equivalent": "sievert",
    "conductance": "siemens",
    "plane_angle": "radian",
}
